In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3], dtype="int16")
a

array([1, 2, 3], dtype=int16)

In [3]:
b = np.array([[2.0,3.0,4.0],[6.0,8.0,7.0],[8.0,9.0,7.0]])
b
print(b)

[[2. 3. 4.]
 [6. 8. 7.]
 [8. 9. 7.]]


In [4]:
#for number of dimensions
a.ndim

1

In [5]:
b.ndim

2

In [6]:
#for shape(i.e. the kind of matrices it falls under)
a.shape

(3,)

In [7]:
b.shape

(3, 3)

In [8]:
#for type(the kind of data type it falls)
a.dtype

dtype('int16')

In [9]:
#recall that a float (has a decimal point)
#floats by default has 64 numbers 
b.dtype

dtype('float64')

In [10]:
#for item size
#The size is the number of bytes in the array..
a.itemsize

2

In [11]:
#for total number of elements
a.size

3

In [12]:
#for total number of size=total number of element*total number of item size
a.size*a.itemsize

6

In [13]:
#or for total number of size= nbytes wher n is the number of bytes in the array
a.nbytes

6

In [14]:
#Accessing, changing specific rows and columns
c = np.array([[3,4,4,6,7,7,8],[8,3,2,2,1,4,5]])
print (c)

[[3 4 4 6 7 7 8]
 [8 3 2 2 1 4 5]]


In [15]:
#the shape gives the kind of matrix representation.. 
c.shape

(2, 7)

In [16]:
#to select an element from the group of array
c[1,5]

4

In [17]:
#to select an element from group of array from backward form
c[1,-2]

4

In [18]:
# to get specific rows 
c[0,:]

array([3, 4, 4, 6, 7, 7, 8])

In [19]:
c[1,:]

array([8, 3, 2, 2, 1, 4, 5])

In [20]:
#to get a specific column
c[:,1]

array([4, 3])

In [21]:
d = np.array([[[2,2,2],[3,-8,9]],[[4,5,5],[3,7,-9]]])
print(d)

[[[ 2  2  2]
  [ 3 -8  9]]

 [[ 4  5  5]
  [ 3  7 -9]]]


In [22]:
#This is for a more fancy way of representing matrices
#First box of matrix,row,column
d[0,1,1]

-8

In [23]:
d.ndim

3

In [24]:
d.max()

9

In [25]:
#For one by one matrix
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
#for zero matrices
np.zeros((3,5), dtype='int32')

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [27]:
#For any number
np.full((4,3), 10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [28]:
#for anyother number just like the matrices above in your codes
np.full_like(d, 4)

array([[[4, 4, 4],
        [4, 4, 4]],

       [[4, 4, 4],
        [4, 4, 4]]])

In [29]:
#another way of writing anyother number in the matrices
np.full(d.shape, 4)

array([[[4, 4, 4],
        [4, 4, 4]],

       [[4, 4, 4],
        [4, 4, 4]]])

In [30]:
np.random.rand(3,6)

array([[0.37383995, 0.99384139, 0.58058375, 0.29465054, 0.03978211,
        0.21340316],
       [0.91440563, 0.48293076, 0.40415013, 0.01131602, 0.02179455,
        0.00646362],
       [0.57895512, 0.98175225, 0.74363667, 0.06971771, 0.80804204,
        0.83097792]])

In [31]:
np.random.rand(20)

array([0.01673685, 0.5288156 , 0.1371391 , 0.25942511, 0.62467923,
       0.61339862, 0.93364042, 0.40241667, 0.50483137, 0.94523034,
       0.3965455 , 0.85397112, 0.12932398, 0.84048185, 0.3020742 ,
       0.89671854, 0.66068472, 0.77771199, 0.78243077, 0.74606039])

In [32]:
np.random.rand(5,3,2)

array([[[0.74970463, 0.89701652],
        [0.44269794, 0.29852411],
        [0.27761747, 0.48001494]],

       [[0.13443536, 0.2457303 ],
        [0.0503932 , 0.6409785 ],
        [0.10261523, 0.60462518]],

       [[0.40060263, 0.33423371],
        [0.62893594, 0.45652791],
        [0.76956531, 0.84253943]],

       [[0.99016863, 0.22193814],
        [0.61114466, 0.65131348],
        [0.6924473 , 0.79792126]],

       [[0.93504178, 0.03312752],
        [0.59670894, 0.23327268],
        [0.13688689, 0.962915  ]]])

In [33]:
#for random matrices less than 3
np.random.randint(3, size=(2,5))

array([[0, 2, 2, 2, 1],
       [1, 0, 1, 2, 1]])

In [34]:
#for random matrices from 3 but less than 8
np.random.randint(3,8, size=(2,5,6))

array([[[6, 6, 5, 7, 7, 3],
        [3, 6, 6, 7, 5, 3],
        [7, 4, 5, 6, 7, 3],
        [7, 5, 7, 7, 4, 4],
        [7, 3, 3, 5, 7, 6]],

       [[4, 6, 6, 3, 4, 3],
        [7, 6, 7, 7, 7, 5],
        [5, 4, 3, 7, 5, 3],
        [4, 3, 3, 4, 7, 7],
        [5, 3, 7, 7, 6, 6]]])

In [35]:
#for identity matrices
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [36]:
#for repeating of matrices
e = np.array([[2,3,-5]])
e1 =np.repeat(e,4, axis=0)
print(e1)

[[ 2  3 -5]
 [ 2  3 -5]
 [ 2  3 -5]
 [ 2  3 -5]]


In [37]:
# A Simple task
# In a 5x5 matrix of ones and zeros, input 9 directly in the middle 
task = np.ones((5,5))
print (task)

r = np.zeros((3,3))
r[1,1] = 9
print (r)

task[1:-1,1:-1] = r
print (task)



[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [38]:
#for copying of numbers
f = np.array([3,4,5])
g = f.copy()
g[0] = 7
print (g)
print (f)

[7 4 5]
[3 4 5]


In [39]:
#for Mathematics performing of trigonometry functions
np.cos(f)

array([-0.9899925 , -0.65364362,  0.28366219])

In [40]:
np.sin(f)

array([ 0.14112001, -0.7568025 , -0.95892427])